"""sync schemas

Revision ID: 020b5bafae16
Revises: 2a7280c85940
Create Date: 2026-08-27 16:42:29.109697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020b5bafae16'
down_revision: Union[str, Sequence[str], None] = '2a7280c85940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cycle_type', sa.String(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_groups_id'), 'cycle_groups', ['id'], unique=False)
    op.add_column('generation_runs', sa.Column('academic_year_id', sa.Integer(), nullable=True))
    op.add_column('generation_runs', sa.Column('generation_type', sa.String(length=50), nullable=False))
    op.add_column('generation_runs', sa.Column('objective_score', sa.Integer(), nullable=True))
    op.add_column('generation_runs', sa.Column('conflict_count', sa.Integer(), nullable=False))
    op.add_column('generation_runs', sa.Column('conflict_details', sa.JSON(), nullable=True))
    op.add_column('generation_runs', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('generation_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('generation_runs', 'timetable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_generation_runs_academic_year_id'), 'generation_runs', ['academic_year_id'], unique=False)
    op.create_foreign_key(None, 'generation_runs', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_column('generation_runs', 'input_version')
    op.drop_column('generation_runs', 'generation_time')
    op.add_column('sections', sa.Column('stream_id', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('cycle_group_id', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('batch_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sections_cycle_group_id'), 'sections', ['cycle_group_id'], unique=False)
    op.create_index(op.f('ix_sections_stream_id'), 'sections', ['stream_id'], unique=False)
    op.create_foreign_key(None, 'sections', 'cycle_groups', ['cycle_group_id'], ['id'])
    op.create_foreign_key(None, 'sections', 'streams', ['stream_id'], ['id'])
    op.add_column('streams', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('streams', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('subjects', sa.Column('stream_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('is_lab', sa.Boolean(), nullable=False))
    op.add_column('subjects', sa.Column('subject_type', sa.String(length=50), nullable=False))
    op.add_column('subjects', sa.Column('weekly_hours', sa.Integer(), nullable=False))
    op.add_column('subjects', sa.Column('cycle_group', sa.String(length=50), nullable=True))
    op.add_column('subjects', sa.Column('scheme', sa.String(length=50), nullable=True))
    op.add_column('subjects', sa.Column('semester_name', sa.String(length=50), nullable=True))
    op.drop_index(op.f('uq_subjects_dept_code'), table_name='subjects')
    op.create_unique_constraint('uq_subjects_dept_code', 'subjects', ['department_id', 'code'])
    op.create_index(op.f('ix_subjects_stream_id'), 'subjects', ['stream_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'streams', ['stream_id'], ['id'])
    op.add_column('timetable_entries', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.add_column('timetable_entries', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('timetable_entries', sa.Column('stream_id', sa.Integer(), nullable=True))
    op.add_column('timetable_entries', sa.Column('cycle_group', sa.String(length=50), nullable=True))
    op.add_column('timetable_entries', sa.Column('paired_slot_group', sa.String(length=50), nullable=True))
    op.alter_column('timetable_entries', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_timetable_entries_batch_id'), 'timetable_entries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_lab_id'), 'timetable_entries', ['lab_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_stream_id'), 'timetable_entries', ['stream_id'], unique=False)
    op.create_foreign_key(None, 'timetable_entries', 'streams', ['stream_id'], ['id'])
    op.create_foreign_key(None, 'timetable_entries', 'batches', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'timetable_entries', 'labs', ['lab_id'], ['id'])
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'local'::character varying"))
    op.drop_index(op.f('ix_users_email_provider'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email_provider', 'users', ['email', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email_provider', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email_provider'), 'users', ['email', 'provider'], unique=True)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'local'::character varying"))
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_index(op.f('ix_timetable_entries_stream_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_lab_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_batch_id'), table_name='timetable_entries')
    op.alter_column('timetable_entries', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('timetable_entries', 'paired_slot_group')
    op.drop_column('timetable_entries', 'cycle_group')
    op.drop_column('timetable_entries', 'stream_id')
    op.drop_column('timetable_entries', 'batch_id')
    op.drop_column('timetable_entries', 'lab_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_stream_id'), table_name='subjects')
    op.drop_constraint('uq_subjects_dept_code', 'subjects', type_='unique')
    op.create_index(op.f('uq_subjects_dept_code'), 'subjects', ['department_id', 'code'], unique=True)
    op.drop_column('subjects', 'semester_name')
    op.drop_column('subjects', 'scheme')
    op.drop_column('subjects', 'cycle_group')
    op.drop_column('subjects', 'weekly_hours')
    op.drop_column('subjects', 'subject_type')
    op.drop_column('subjects', 'is_lab')
    op.drop_column('subjects', 'stream_id')
    op.alter_column('streams', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('streams', 'created_at')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_index(op.f('ix_sections_stream_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_cycle_group_id'), table_name='sections')
    op.drop_column('sections', 'batch_count')
    op.drop_column('sections', 'cycle_group_id')
    op.drop_column('sections', 'stream_id')
    op.add_column('generation_runs', sa.Column('generation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('generation_runs', sa.Column('input_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_generation_runs_academic_year_id'), table_name='generation_runs')
    op.alter_column('generation_runs', 'timetable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('generation_runs', 'completed_at')
    op.drop_column('generation_runs', 'started_at')
    op.drop_column('generation_runs', 'conflict_details')
    op.drop_column('generation_runs', 'conflict_count')
    op.drop_column('generation_runs', 'objective_score')
    op.drop_column('generation_runs', 'generation_type')
    op.drop_column('generation_runs', 'academic_year_id')
    op.drop_index(op.f('ix_cycle_groups_id'), table_name='cycle_groups')
    op.drop_table('cycle_groups')
    # ### end Alembic commands ###
