"""add constraints versioning and generation

Revision ID: 48735e97c095
Revises: a290dc89702f
Create Date: 2026-08-17 01:30:20.109899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48735e97c095'
down_revision: Union[str, Sequence[str], None] = 'a290dc89702f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('hardness', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_id'), 'constraints', ['id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=False),
    sa.Column('generation_time', sa.DateTime(), nullable=False),
    sa.Column('objective_metrics', sa.JSON(), nullable=True),
    sa.Column('error_information', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_id'), 'generation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_runs_timetable_id'), 'generation_runs', ['timetable_id'], unique=False)
    op.create_table('timetable_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_versions_id'), 'timetable_versions', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_versions_timetable_id'), 'timetable_versions', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_versions_timetable_id'), table_name='timetable_versions')
    op.drop_index(op.f('ix_timetable_versions_id'), table_name='timetable_versions')
    op.drop_table('timetable_versions')
    op.drop_index(op.f('ix_generation_runs_timetable_id'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_constraints_id'), table_name='constraints')
    op.drop_table('constraints')
    # ### end Alembic commands ###
