"""add timetable scheduling models

Revision ID: a290dc89702f
Revises: 7d7f1378e8a4
Create Date: 2026-08-17 01:27:50.013654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a290dc89702f'
down_revision: Union[str, Sequence[str], None] = '7d7f1378e8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_offerings_faculty_id'), 'subject_offerings', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_subject_offerings_id'), 'subject_offerings', ['id'], unique=False)
    op.create_index(op.f('ix_subject_offerings_section_id'), 'subject_offerings', ['section_id'], unique=False)
    op.create_index(op.f('ix_subject_offerings_semester_id'), 'subject_offerings', ['semester_id'], unique=False)
    op.create_index(op.f('ix_subject_offerings_subject_id'), 'subject_offerings', ['subject_id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index(op.f('ix_timetables_semester_id'), 'timetables', ['semester_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('subject_offering_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['subject_offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_id'), 'timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_room_id'), 'timetable_entries', ['room_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_subject_offering_id'), 'timetable_entries', ['subject_offering_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_time_slot_id'), 'timetable_entries', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_id'), 'timetable_entries', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_timetable_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_time_slot_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_subject_offering_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_room_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_timetables_semester_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_subject_offerings_subject_id'), table_name='subject_offerings')
    op.drop_index(op.f('ix_subject_offerings_semester_id'), table_name='subject_offerings')
    op.drop_index(op.f('ix_subject_offerings_section_id'), table_name='subject_offerings')
    op.drop_index(op.f('ix_subject_offerings_id'), table_name='subject_offerings')
    op.drop_index(op.f('ix_subject_offerings_faculty_id'), table_name='subject_offerings')
    op.drop_table('subject_offerings')
    # ### end Alembic commands ###
